// Generated by scripts/prepare_character_animation.py --catalog-header.
// Calibration and provenance: resources/characters/catalog.json and evidence/.
#ifndef CORE_ANIMATION_CHARACTER_CATALOG_HPP
#define CORE_ANIMATION_CHARACTER_CATALOG_HPP

#include <array>
#include <cstddef>
#include <limits>
#include <string_view>

struct CharacterCatalogEntry {
  std::string_view id;
  std::string_view resource;
  std::array<float, 3> feet_origin;
  std::array<float, 3> forward_axis;
  float capsule_radius_m;
  float capsule_height_m;
  std::array<float, 3> preview_min;
  std::array<float, 3> preview_max;
  double walk_cycle_distance_m;
  std::array<double, 2> walk_contact_phases;
  double interaction_phase;
  double minimum_speed_m_s;
  double maximum_speed_m_s;
};

[[nodiscard]] constexpr bool characterCatalogIsValid(const CharacterCatalogEntry& entry) {
  const auto finite = [](double value) {
    return value >= -std::numeric_limits<double>::max() && value <= std::numeric_limits<double>::max();
  };
  double forward_length_squared = 0;
  for (std::size_t axis = 0; axis < 3; ++axis) {
    if (!finite(entry.feet_origin[axis]) || !finite(entry.forward_axis[axis]) ||
        !finite(entry.preview_min[axis]) || !finite(entry.preview_max[axis]) ||
        entry.preview_min[axis] >= entry.preview_max[axis] ||
        entry.feet_origin[axis] < entry.preview_min[axis] || entry.feet_origin[axis] > entry.preview_max[axis]) return false;
    forward_length_squared += static_cast<double>(entry.forward_axis[axis]) * entry.forward_axis[axis];
  }
  const double first = entry.walk_contact_phases[0], second = entry.walk_contact_phases[1];
  const double spacing = (second-first < 1+first-second ? second-first : 1+first-second);
  return !entry.id.empty() && !entry.resource.empty() &&
         forward_length_squared >= 0.99999 && forward_length_squared <= 1.00001 &&
         finite(entry.capsule_radius_m) && entry.capsule_radius_m > 0 &&
         finite(entry.capsule_height_m) && entry.capsule_height_m >= 2*entry.capsule_radius_m &&
         finite(entry.walk_cycle_distance_m) && entry.walk_cycle_distance_m > 0 &&
         finite(entry.minimum_speed_m_s) && finite(entry.maximum_speed_m_s) &&
         entry.minimum_speed_m_s >= 0.25 && entry.minimum_speed_m_s <= entry.maximum_speed_m_s &&
         entry.maximum_speed_m_s <= 1.5 && first >= 0 && first < second && second < 1 &&
         entry.interaction_phase > 0 && entry.interaction_phase < 1 &&
         spacing*entry.walk_cycle_distance_m/entry.maximum_speed_m_s >= 0.20;
}

inline constexpr CharacterCatalogEntry test_mannequin_catalog{
    "test-mannequin", "characters/test-mannequin.glb",
    {0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 1.0F},
    0.25F, 1.85F,
    {-1.05F, -0.1F, -0.55F}, {1.05F, 1.9F, 0.8F},
    1.3061969054512663,
    {0.0, 0.5},
    0.36666666666666664,
    0.25, 1.5};

static_assert(characterCatalogIsValid(test_mannequin_catalog));

#endif
